{
  "openapi": "3.0.3",
  "info": {
    "title": "Gristle API",
    "description": "API documentation for Gristle document parsing services, based on the OpenAPI 3.0 specification.\n\nAll API calls can be accessed using _Basic Authentication_, an authentication token is returned with every response as an optional form of authentication for future requests.\n\nIf you're simply pushing files to be parsed jump to the [parse service call](#/parse/postInvokeParser) section, as it's likely all you need.  The traditional workflow of which goes as follows:\n\n- Uplo[...]",
    "contact": {
      "email": "support@gristle.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://api.gristle.com"
    }
  ],
  "tags": [
    {
      "name": "user",
      "description": "User settings and authentication"
    },
    {
      "name": "parse",
      "description": "Upload files to a parser for processing and download the corresponding outputs"
    },
    {
      "name": "parser",
      "description": "Review and update parser settings"
    },
    {
      "name": "map",
      "description": "Associate a document file to a parser for future mapping (required to parse)"
    },
    {
      "name": "issue",
      "description": "Submit and review issues (tickets) for parsers, parsed outputs, and overall account"
    }
  ],
  "paths": {
    "/user": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Get user settings",
        "description": "This can also act as _/user/auth_, the username and password are provided via _Basic Authentication_.",
        "operationId": "getUserByName",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Create or update user settings",
        "description": "Create or update user settings, __all outside authentication tokens are wiped upon update__. The username and password are provided via _Basic Authentication_.",
        "operationId": "updateUserByName",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/user/auth": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Get an authentication token",
        "description": "Return an authentication (_Bearer_) token from a username and password using _Basic Authentication_.  Any path can include this _Basic Authentication_, which may make this a redundant and unnecessary step for some use-cases.  The header _GRISTLE-TOKEN_ can be used instead of the _Bearer_ authentication model, for ease of use with various tools like _curl_.",
        "operationId": "login",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/user/verify": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Send an email to verify the user's email",
        "description": "Send an email to verify the user's email.  The email comes from @gristle.net.",
        "operationId": "sendUserEmailToVerify",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/user/verify/{code}": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Send back the emailed code to verify the user's email",
        "description": "Send back the emailed code to verify the user's email  The email comes from @gristle.net.",
        "operationId": "verifyUserEmail",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/user/{username}": {
      "head": {
        "tags": [
          "user"
        ],
        "summary": "Determine if a user exists",
        "description": "Determine if a user exists.",
        "operationId": "findUserByName"
      }
    },
    "/parse/{parserId}": {
      "get": {
        "tags": [
          "parse"
        ],
        "summary": "Return a list of uploads for a parser",
        "description": "Return a list of parsed outputs and unprocessed uploads for a parser.  Results are in the _parses_ portion of the returned JSON.",
        "operationId": "getParsedList",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "parse"
        ],
        "summary": "Upload a file to a parser for processing",
        "description": "Upload a file to a parser for processing using HTTP multipart/form-data.  For tracking, the _id_ returned in the JSON is referenced as _uploadId_ with future requests.  The HTTP header _Gristle-Parse-Id_ also provides the _id_.",
        "operationId": "postInvokeParser",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/parse/{parserId}/{uploadId}": {
      "get": {
        "tags": [
          "parse"
        ],
        "summary": "Get the parsed output of an uploaded file",
        "description": "Download the parsed output of an uploaded file using the _uploadId_.",
        "operationId": "getParsedOutput",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "parse"
        ],
        "summary": "Deletes an uploaded file and/or its parsed output",
        "description": "Deletes an uploaded file and/or its parsed output.",
        "operationId": "deleteParsedOutput",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "parse"
        ],
        "summary": "Check if an uploaded file has been parsed",
        "description": "Check to see if an uploaded file has been parsed and its corresponding output is ready to download, without downloading it.",
        "operationId": "checkParsedOutput",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/parser": {
      "get": {
        "tags": [
          "parser"
        ],
        "summary": "List all available parsers",
        "description": "Return a list of all available parsers.  Results are in the _parsers_ portion of the returned JSON.",
        "operationId": "getParsers",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/parser/{parserId}": {
      "get": {
        "tags": [
          "parser"
        ],
        "summary": "Get parser details by ID",
        "description": "Return a parsers details by its parser ID.",
        "operationId": "getParserById",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "parser"
        ],
        "summary": "Update parser details by ID",
        "description": "Update parser details",
        "operationId": "postParserById",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "parser"
        ],
        "summary": "Delete a parser",
        "description": "Delete a parser",
        "operationId": "deleteParser",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/map/{parserId}": {
      "get": {
        "tags": [
          "map"
        ],
        "summary": "Get the current mapping data for a parser",
        "description": "Get the current mapping rules associated to a mapping document for a parser.",
        "operationId": "getMapParser",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "map"
        ],
        "summary": "Upload a file and associate it to a parser for future mapping",
        "description": "Upload a file and associate it to a parser for future mapping.  __The file used should be the most complex version of the kind of file you intended to parse to capture edge cases.__",
        "operationId": "addMapParser",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "map"
        ],
        "summary": "Delete the mapping data for a parser",
        "description": "Remove the mapping rules and mapping file association from a parser.",
        "operationId": "deleteAllMapParser",
        "security": [
          {
            "basic_auth": [
              "write:parsers",
              "read:parsers"
            ]
          },
          {
            "bearer_auth": [
              "write:parsers",
              "read:parsers"
            ]
          }
        ]
      }
    },
    "/issue": {
      "get": {
        "tags": [
          "issue"
        ],
        "summary": "List all available issues",
        "description": "Return a list of all available issues.  Results are in the _issues_ portion of the returned JSON.",
        "operationId": "getIssues",
        "security": [
          {
            "basic_auth": [
              "write:issues",
              "read:issues"
            ]
          },
          {
            "bearer_auth": [
              "write:issues",
              "read:issues"
            ]
          }
        ]
      }
    },
    "/issue/{assortedId}": {
      "get": {
        "tags": [
          "issue"
        ],
        "summary": "Get issue details by ID",
        "description": "Return the issue discussion data by ID.  Discussion data is in the _data_ portion of the returned JSON.",
        "operationId": "getIssueById",
        "security": [
          {
            "basic_auth": [
              "write:issues",
              "read:issues"
            ]
          },
          {
            "bearer_auth": [
              "write:issues",
              "read:issues"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "issue"
        ],
        "summary": "Create or add to an issue by ID",
        "description": "Create or add to an issue by ID.",
        "operationId": "postIssueById",
        "security": [
          {
            "basic_auth": [
              "write:issues",
              "read:issues"
            ]
          },
          {
            "bearer_auth": [
              "write:issues",
              "read:issues"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "issue"
        ],
        "summary": "Delete an issue by ID",
        "description": "Delete an issue by ID.",
        "operationId": "deleteIssue",
        "security": [
          {
            "basic_auth": [
              "write:issues",
              "read:issues"
            ]
          },
          {
            "bearer_auth": [
              "write:issues",
              "read:issues"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "basic_auth": {
        "type": "http",
        "scheme": "basic"
      },
      "bearer_auth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}